spring:

  data:
    mongodb:
      port: 0 # when flapdoodle using
      database: books

  aop:
    proxy-target-class: false

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 7.0.14

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  migration-scan-package: ru.otus.hw.changelog
  transactional: false
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

